create table db_field_widget_config
(
    id                     bigint auto_increment comment '主键ID'
        primary key,
    table_id               bigint                             null comment '所属表ID（关联db_table.id），为空表示默认映射规则',
    field_id               bigint                             null comment '字段ID（关联db_table_field.id），为空表示默认映射规则',
    widget_type            varchar(50)                        not null comment '控件类型（input/textarea/select/radio/checkbox/switch/date/datetime/number/upload/cascader等）',
    widget_config          text                               null comment '控件配置JSON（placeholder/默认值/校验规则/控件属性等）',
    is_default             tinyint  default 0                 not null comment '是否为默认映射规则：1-是，0-否',
    default_for_field_type varchar(50)                        null comment '作为默认映射的字段类型（VARCHAR/INT/DATETIME等）',
    enabled                tinyint  default 1                 not null comment '是否启用：1-启用，0-禁用',
    sort_order             int      default 0                 not null comment '排序序号',
    create_time            datetime default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time            datetime default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    deleted                tinyint  default 0                 not null comment '逻辑删除：1-删除，0-存在',
    constraint uk_table_field
        unique (table_id, field_id, deleted)
)
    comment '字段-控件绑定配置表';

create index idx_default_for_field_type
    on db_field_widget_config (default_for_field_type);

create index idx_enabled
    on db_field_widget_config (enabled);

create index idx_field_id
    on db_field_widget_config (field_id);

create index idx_is_default
    on db_field_widget_config (is_default);

create index idx_table_id
    on db_field_widget_config (table_id);

INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (1, null, null, 'input', '{"placeholder":"请输入...","required":false,"span":12}', 1, 'VARCHAR', 1, 1, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (2, null, null, 'textarea', '{"placeholder":"请输入...","rows":3,"required":false,"span":24}', 1, 'TEXT', 1, 2, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (3, null, null, 'input', '{"placeholder":"请输入...","required":false,"span":12}', 1, 'CHAR', 1, 3, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (4, null, null, 'select', '{"placeholder":"请选择...","required":false,"span":12,"options":[]}', 1, 'ENUM', 1, 4, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (5, null, null, 'number', '{"placeholder":"请输入数字","required":false,"span":12}', 1, 'INT', 1, 5, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (6, null, null, 'number', '{"placeholder":"请输入数字","required":false,"span":12}', 1, 'BIGINT', 1, 6, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (7, null, null, 'number', '{"placeholder":"请输入数字","required":false,"span":12}', 1, 'DECIMAL', 1, 7, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (8, null, null, 'number', '{"placeholder":"请输入数字","required":false,"span":12}', 1, 'FLOAT', 1, 8, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (9, null, null, 'number', '{"placeholder":"请输入数字","required":false,"span":12}', 1, 'DOUBLE', 1, 9, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (10, null, null, 'date', '{"placeholder":"请选择日期","required":false,"span":12,"format":"YYYY-MM-DD"}', 1, 'DATE', 1, 10, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (11, null, null, 'datetime', '{"placeholder":"请选择日期时间","required":false,"span":12}', 1, 'DATETIME', 1, 11, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (12, null, null, 'datetime', '{"placeholder":"请选择日期时间","required":false,"span":12}', 1, 'TIMESTAMP', 1, 12, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (13, null, null, 'time', '{"placeholder":"请选择时间","required":false,"span":12}', 1, 'TIME', 1, 13, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (14, null, null, 'switch', '{"required":false,"span":12}', 1, 'BOOLEAN', 1, 14, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (15, null, null, 'switch', '{"required":false,"span":12}', 1, 'TINYINT', 1, 15, '2026-02-01 16:21:55', '2026-02-01 16:21:55', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (16, 6, 90, 'number', '{"placeholder":"请输入表单ID","required":true,"span":12,"label":"表单ID"}', 0, null, 1, 1, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (17, 6, 91, 'input', '{"placeholder":"请输入表单名称","required":true,"span":12,"label":"表单名称"}', 0, null, 1, 2, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (18, 6, 92, 'input', '{"placeholder":"请输入表单编码","required":false,"span":12,"label":"表单编码"}', 0, null, 1, 3, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (19, 6, 93, 'input', '{"placeholder":"请输入表单类型(add/edit/search/detail/dialog)","required":false,"span":12,"label":"表单类型(add/edit/search/detail/dialog)"}', 0, null, 1, 4, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (20, 6, 94, 'input', '{"placeholder":"请输入布局类型(horizontal/vertical/inline)","required":false,"span":12,"label":"布局类型(horizontal/vertical/inline)","defaultValue":"horizontal"}', 0, null, 1, 5, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (21, 6, 95, 'number', '{"placeholder":"请输入表单列数","required":false,"span":12,"label":"表单列数","defaultValue":"2"}', 0, null, 1, 6, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (22, 6, 96, 'number', '{"placeholder":"请输入标签宽度","required":false,"span":12,"label":"标签宽度","defaultValue":"100"}', 0, null, 1, 7, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (23, 6, 97, 'input', '{"placeholder":"请输入标签位置(left/right/top)","required":false,"span":12,"label":"标签位置(left/right/top)","defaultValue":"right"}', 0, null, 1, 8, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (24, 6, 98, 'input', '{"placeholder":"请输入组件尺寸(large/default/small)","required":false,"span":12,"label":"组件尺寸(large/default/small)","defaultValue":"default"}', 0, null, 1, 9, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (25, 6, 99, 'textarea', '{"placeholder":"请输入表单配置JSON","rows":3,"required":false,"span":24,"label":"表单配置JSON"}', 0, null, 1, 10, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (26, 6, 100, 'textarea', '{"placeholder":"请输入校验规则JSON","rows":3,"required":false,"span":24,"label":"校验规则JSON"}', 0, null, 1, 11, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (27, 6, 101, 'switch', '{"required":false,"span":12,"label":"状态","placeholder":"请输入状态","defaultValue":"1"}', 0, null, 1, 12, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (28, 6, 102, 'switch', '{"required":false,"span":12,"label":"是否删除","placeholder":"请输入是否删除","defaultValue":"0"}', 0, null, 1, 13, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (29, 6, 103, 'input', '{"placeholder":"请输入创建者","required":false,"span":12,"label":"创建者"}', 0, null, 1, 14, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (30, 6, 104, 'datetime', '{"placeholder":"请选择创建时间","required":false,"span":12,"label":"创建时间","defaultValue":"CURRENT_TIMESTAMP"}', 0, null, 1, 15, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (31, 6, 105, 'datetime', '{"placeholder":"请选择更新时间","required":false,"span":12,"label":"更新时间","defaultValue":"CURRENT_TIMESTAMP"}', 0, null, 1, 16, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (32, 6, 106, 'input', '{"placeholder":"请输入ç»„ä»¶åˆ†ç±»: common=é€šç”¨ç»„ä»¶åº“, business=ä¸šåŠ¡ç»„ä»¶åº“","required":false,"span":12,"label":"ç»„ä»¶åˆ†ç±»: common=é€šç”¨ç»„ä»¶åº“, business=ä¸šåŠ¡ç»„ä»¶åº“","defaultValue":"business"}', 0, null, 1, 17, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
INSERT INTO lowcode_platform.db_field_widget_config (id, table_id, field_id, widget_type, widget_config, is_default, default_for_field_type, enabled, sort_order, create_time, update_time, deleted) VALUES (33, 6, 107, 'textarea', '{"placeholder":"请输入ç»„ä»¶æ\\u00a0‡ç­¾JSON: [\\"system\\",\\"user\\"]","rows":3,"required":false,"span":24,"label":"ç»„ä»¶æ\\u00a0‡ç­¾JSON: [\\"system\\",\\"user\\"]"}', 0, null, 1, 18, '2026-02-01 16:22:22', '2026-02-01 16:22:22', 0);
