create table sys_menu
(
    id             bigint auto_increment comment '菜单ID'
        primary key,
    parent_id      bigint   default 0                 null comment '父菜单ID',
    menu_name      varchar(50)                        not null comment '菜单名称',
    menu_code      varchar(50)                        null comment '菜单编码',
    menu_type      tinyint                            null comment '菜单类型(1目录 2菜单 3按钮)',
    icon           varchar(100)                       null comment '菜单图标',
    sort_order     int      default 0                 null comment '排序',
    route_path     varchar(200)                       null comment '路由地址',
    component_path varchar(200)                       null comment '组件路径',
    page_id        bigint                             null comment '关联页面ID',
    is_external    tinyint  default 0                 null comment '是否外链(0否 1是)',
    external_url   varchar(500)                       null comment '外链地址',
    visible        tinyint  default 1                 null comment '是否可见',
    status         tinyint  default 1                 null comment '状态(0停用 1启用)',
    perms          varchar(100)                       null comment '权限标识',
    deleted        tinyint  default 0                 null comment '是否删除',
    create_time    datetime default CURRENT_TIMESTAMP null comment '创建时间',
    update_time    datetime default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP comment '更新时间'
)
    comment '菜单配置表';

create index idx_parent_id
    on sys_menu (parent_id);

create index idx_status
    on sys_menu (status);

INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (0, '系统管理', 'system', 1, 'Setting', 888, '/system', '', null, 0, null, 1, 1, null, 0, '2026-01-28 17:01:19', '2026-01-28 17:01:19');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (0, '低代码配置', 'lowcode', 1, 'Edit', 999, '/lowcode', '', null, 0, null, 1, 1, null, 0, '2026-01-28 17:01:19', '2026-01-28 17:01:19');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (1, '用户管理', 'system:user', 2, 'User', 1, '/system/user', '/views/system/UserManage.vue', null, 0, null, 1, 1, null, 1, '2026-01-28 17:01:19', '2026-04-10 16:05:03');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (1, '菜单管理', 'system:menu', 2, 'Menu', 2, '/system/menu', '/views/system/MenuManage.vue', null, 0, null, 1, 1, null, 0, '2026-01-28 17:01:19', '2026-01-28 17:01:19');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (1, '字典管理', 'system:dict', 2, 'Collection', 3, '/system/dict', '/views/system/DictManage.vue', null, 0, null, 1, 1, null, 0, '2026-01-28 17:01:19', '2026-01-28 17:01:19');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '页面管理', 'lowcode:page', 2, 'Document', 1, '/lowcode/PageManage', '/views/lowcode-v6/PageManageV6.vue', null, 0, null, 1, 1, null, 0, '2026-01-28 17:01:19', '2026-02-01 11:33:15');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '表单管理', 'lowcode:form', 2, 'Document', 2, '/lowcode/FormManage', '/views/lowcode/FormManage.vue', null, 0, null, 1, 1, 'lowcode:button:list', 0, '2026-01-28 17:01:19', '2026-02-02 23:52:27');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '表格管理', 'lowcode:table', 2, 'Grid', 3, '/lowcode/TableManage', '/views/lowcode/TableManage.vue', null, 0, null, 1, 1, 'lowcode:button:list', 0, '2026-01-28 17:01:19', '2026-02-02 23:52:27');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (2, '模板管理', 'lowcode:template', 2, 'Files', 4, '/lowcode/template', '/views/lowcode/TemplateManage.vue', null, 0, null, 1, 1, null, 1, '2026-01-28 17:01:19', '2026-04-10 16:05:07');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (22, '按钮管理', 'lowcode:button', 2, 'Setting', 5, '/lowcode/ButtonLibrary', 'views/lowcode/ButtonLibrary.vue', null, 0, null, 1, 1, 'lowcode:button:list', 0, '2026-01-30 23:54:27', '2026-01-31 00:25:36');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (2, 'V4用户测试', 'v4:user:test', 2, 'User', 99, '/v4-user-test', null, 34, 0, null, 1, 1, null, 1, '2026-01-31 18:05:00', '2026-02-01 10:45:15');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (22, '库表管理', 'lowcodetable', 2, 'Database', 100, '/lowcode/DbTableManage', '/views/lowcode/DbTableList.vue', null, 0, null, 1, 1, null, 0, '2026-02-01 14:11:18', '2026-02-01 16:28:52');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (22, '字段-控件绑定', 'field_widget_binding', 2, 'Link', 6, '/lowcode/FieldWidgetBinding', '/views/lowcode/FieldWidgetBinding.vue', null, 0, null, 1, 1, null, 0, '2026-02-01 16:20:34', '2026-02-01 16:28:52');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (22, '下拉管理', 'lowcode:dropdown', 2, 'ArrowDown', 8, '/lowcode/DropdownManage', '/views/lowcode/DropdownManage.vue', null, 0, null, 1, 1, null, 0, '2026-02-02 21:08:41', '2026-02-02 21:08:41');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (2, '下拉管理', 'lowcode:dropdown', 2, 'ArrowDown', 8, '/lowcode/DropdownManage', '/views/lowcode/DropdownManage.vue', null, 0, null, 1, 1, null, 1, '2026-02-02 21:09:24', '2026-02-02 21:12:43');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (2, '页面布局', 'lowcode:page_layout', 2, 'Grid', 15, '/lowcode/PageLayoutManage', '/views/lowcode/PageLayoutManage.vue', null, 0, null, 1, 1, null, 1, '2026-02-02 23:52:27', '2026-04-15 19:06:24');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (22, '表单字段绑定', 'lowcode:form_field_binding', 2, 'Link', 1, '/lowcode/FormFieldBinding', '/views/lowcode/FormFieldBinding.vue', null, 0, null, 0, 1, null, 0, '2026-02-02 23:52:27', '2026-02-02 23:52:27');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (22, '表格列绑定', 'lowcode:table_column_binding', 2, 'Link', 1, '/lowcode/TableColumnBinding', '/views/lowcode/TableColumnBinding.vue', null, 0, null, 0, 1, null, 0, '2026-02-02 23:52:27', '2026-02-02 23:52:27');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '表单样式模板', 'lowcode:form_style_template', 2, 'Brush', 18, '/lowcode/FormStyleTemplateManage', '/views/lowcode/FormStyleTemplateManage.vue', null, 0, null, 1, 1, null, 0, '2026-02-03 00:25:53', '2026-02-03 00:32:23');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '表格样式模板', 'lowcode:table_style_template', 2, 'Grid', 19, '/lowcode/TableStyleTemplateManage', '/views/lowcode/TableStyleTemplateManage.vue', null, 0, null, 1, 1, null, 0, '2026-02-03 00:25:53', '2026-02-03 00:32:24');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (0, '测试目录', '1', 1, '', 0, '', '', null, 0, null, 1, 1, null, 1, '2026-02-03 21:06:48', '2026-04-10 16:04:38');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (2, '后端', 'hd', 1, '', 200, '', '', null, 0, null, 1, 1, null, 0, '2026-01-28 17:01:19', '2026-01-28 17:01:19');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (2, '前端', 'qd', 1, '', 100, '', '', null, 0, null, 1, 1, null, 0, '2026-01-28 17:01:19', '2026-01-28 17:01:19');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (0, '111', '11', 2, '', 0, '/ggee', '/views/lowcode/PageRender.vue', 35, 0, null, 1, 0, null, 0, '2026-02-03 23:09:15', '2026-02-03 23:09:15');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '数据集管理', 'dataset_manage', 2, 'Database', 100, '/dataset/Manage', '/views/dataset/DatasetManage.vue', null, 0, null, 1, 1, null, 1, '2026-03-04 14:44:21', '2026-04-10 16:03:56');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '页面设计器（新版）', 'page_designer_new', 2, 'Edit', 101, '/page/DesignerNew', '/views/page/PageDesignerNew.vue', null, 0, null, 1, 1, null, 1, '2026-03-04 14:44:21', '2026-04-10 16:02:52');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '表单设计器（新版）', 'form_designer_new', 2, 'Edit', 102, '/form/DesignerNew', '/views/form/FormDesignerNew.vue', null, 0, null, 1, 1, null, 1, '2026-03-04 15:12:43', '2026-04-10 16:02:51');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '表格设计器（新版）', 'table_designer_new', 2, 'Edit', 103, '/table/DesignerNew', '/views/table/TableDesignerNew.vue', null, 0, null, 1, 1, null, 1, '2026-03-04 15:12:43', '2026-04-10 16:02:48');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '数据字典管理', 'dict_manage', 2, 'Notebook', 50, '/dict/Manage', null, null, 0, null, 1, 1, null, 1, '2026-03-05 08:39:51', '2026-04-10 16:04:14');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (23, '字段联动配置', 'field_linkage_manage', 2, 'Connection', 60, '/field-linkage/Manage', null, null, 0, null, 1, 1, null, 1, '2026-03-05 08:39:51', '2026-04-10 16:04:12');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (0, '低代码管理', 'lowcode_new', 1, 'Grid', 100, null, null, null, 0, null, 1, 1, null, 1, '2026-03-05 18:17:23', '2026-04-10 16:05:01');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (36, '数据集管理', 'dataset_manage_new', 2, 'Database', 1, '/dataset/Manage', '/views/dataset/DatasetManage.vue', null, 0, null, 1, 1, null, 1, '2026-03-05 18:17:23', '2026-04-10 16:02:55');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (36, '表单管理', 'form_manage_new', 2, 'List', 2, '/form/ManageNew', '/views/form/FormManageNew.vue', null, 0, null, 1, 1, null, 1, '2026-03-05 18:17:23', '2026-04-10 16:04:57');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (36, '表格管理', 'table_manage_new', 2, 'Grid', 3, '/table/ManageNew', '/views/table/TableManageNew.vue', null, 0, null, 1, 1, null, 1, '2026-03-05 18:17:23', '2026-04-10 16:04:58');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (36, '页面管理', 'page_manage_new', 2, 'Document', 4, '/page/ManageNew', '/views/page/PageManageNew.vue', null, 0, null, 1, 1, null, 1, '2026-03-05 18:17:23', '2026-04-10 16:04:59');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (0, '测试案例', 'csal', 1, '', 1, 'csal', '', null, 0, null, 1, 1, null, 0, '2026-04-16 15:20:07', '2026-04-16 15:20:07');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (41, '页面', '3', 2, '', 0, '/free-canvas/m3333', '/views/lowcode/PageRender.vue', 37, 0, null, 1, 0, null, 0, '2026-04-16 15:20:26', '2026-04-16 15:20:26');
INSERT INTO lowcode_platform.sys_menu (parent_id, menu_name, menu_code, menu_type, icon, sort_order, route_path, component_path, page_id, is_external, external_url, visible, status, perms, deleted, create_time, update_time) VALUES (41, '1333', '123', 2, '', 0, '/m3333', '/views/lowcode/PageRender.vue', 37, 0, null, 1, 1, null, 0, '2026-04-16 15:23:03', '2026-04-16 15:23:03');
